import * as THREE from 'three';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';

const app=document.getElementById('app');
const scene=new THREE.Scene(); scene.background=new THREE.Color(0x01040b);
const camera=new THREE.PerspectiveCamera(40,innerWidth/innerHeight,.1,100); camera.position.z=8.8;
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'}); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.setSize(innerWidth,innerHeight); renderer.outputColorSpace=THREE.SRGBColorSpace; renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=1.05; app.appendChild(renderer.domElement);
const composer=new EffectComposer(renderer); composer.addPass(new RenderPass(scene,camera)); composer.addPass(new UnrealBloomPass(new THREE.Vector2(innerWidth,innerHeight),1.22,.48,.05));
const root=new THREE.Group(); scene.add(root);
const C={red:0xff2447,gold:0xffb01e,warm:0xffd69a,white:0xffffff,soft:0xfff5df,blue:0x83d8ff};
function seeded(seed){let s=seed>>>0;return()=>{s=(s*1664525+1013904223)>>>0;return s/4294967296}} const rnd=seeded(22112003);
function tex(){const c=document.createElement('canvas');c.width=c.height=128;const x=c.getContext('2d'),g=x.createRadialGradient(64,64,0,64,64,64);g.addColorStop(0,'rgba(255,255,255,1)');g.addColorStop(.12,'rgba(255,255,255,.96)');g.addColorStop(.3,'rgba(255,225,165,.52)');g.addColorStop(.62,'rgba(255,90,65,.11)');g.addColorStop(1,'rgba(0,0,0,0)');x.fillStyle=g;x.fillRect(0,0,128,128);return new THREE.CanvasTexture(c)} const glow=tex();
function sprite(color,size,opacity=1){const m=new THREE.SpriteMaterial({map:glow,color,transparent:true,opacity,blending:THREE.AdditiveBlending,depthWrite:false});const s=new THREE.Sprite(m);s.scale.setScalar(size);return s}
// sparse background dust
{const n=620,p=new Float32Array(n*3),co=new Float32Array(n*3),pal=[new THREE.Color(C.red),new THREE.Color(C.gold),new THREE.Color(C.soft),new THREE.Color(C.blue)];for(let i=0;i<n;i++){const r=2+rnd()*6.2,a=rnd()*Math.PI*2,ys=.48+rnd()*.46;p[i*3]=Math.cos(a)*r;p[i*3+1]=Math.sin(a)*r*ys;p[i*3+2]=(rnd()-.5)*1.7;const q=pal[Math.floor(rnd()*pal.length)];co[i*3]=q.r;co[i*3+1]=q.g;co[i*3+2]=q.b}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(p,3));g.setAttribute('color',new THREE.BufferAttribute(co,3));root.add(new THREE.Points(g,new THREE.PointsMaterial({size:.018,vertexColors:true,transparent:true,opacity:.58,blending:THREE.AdditiveBlending,depthWrite:false})))}
// outer broken paths
const orbits=[],orbitGroup=new THREE.Group();root.add(orbitGroup);
function makeOrbit(i){const rx=2.35+rnd()*1.55,ry=.72+rnd()*1.05,z=rnd()*Math.PI,x=(rnd()-.5)*.82,y=(rnd()-.5)*.46,off=new THREE.Vector3((rnd()-.5)*.26,(rnd()-.5)*.20,(rnd()-.5)*.16),color=i%3===0?C.gold:C.red,pts=[],start=rnd()*Math.PI*2,span=Math.PI*(1.58+rnd()*.32);for(let k=0;k<220;k++){const t=start+k/219*span;pts.push(new THREE.Vector3(Math.cos(t)*rx,Math.sin(t)*ry,0))}const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color,transparent:true,opacity:.16,blending:THREE.AdditiveBlending}));line.rotation.set(x,y,z);line.position.copy(off);orbitGroup.add(line);const d={rx,ry,line};orbits.push(d);for(let n=0;n<2+Math.floor(rnd()*3);n++){const s=sprite(n%3===0?C.soft:color,.11+rnd()*.05,.82);s.userData={angle:rnd()*Math.PI*2,speed:(.07+rnd()*.1)*(rnd()>.5?1:-1),orbit:d};orbitGroup.add(s)}} for(let i=0;i<7;i++)makeOrbit(i);
function orbitPoint(d,a){const p=new THREE.Vector3(Math.cos(a)*d.rx,Math.sin(a)*d.ry,0);p.applyEuler(d.line.rotation);return p.add(d.line.position)}
// ORGANIC CORE: no concentric ring group at all
const core=new THREE.Group();root.add(core);const points=[],positions=[],colors=[],pal=[new THREE.Color(C.white),new THREE.Color(C.soft),new THREE.Color(C.warm),new THREE.Color(C.gold)];
for(let i=0;i<270;i++){const a=rnd()*Math.PI*2,rr=Math.pow(rnd(),.48)*1.15,w=1+.14*Math.sin(3*a+.6)+.08*Math.sin(7*a+1.4)+.045*Math.sin(11*a);const p=new THREE.Vector3(Math.cos(a)*rr*w,Math.sin(a)*rr*w*.9,(rnd()-.5)*.24);points.push(p);positions.push(p.x,p.y,p.z);const q=pal[Math.floor(rnd()*pal.length)];colors.push(q.r,q.g,q.b)}
const pg=new THREE.BufferGeometry();pg.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));pg.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));core.add(new THREE.Points(pg,new THREE.PointsMaterial({size:.024,vertexColors:true,transparent:true,opacity:.9,blending:THREE.AdditiveBlending,depthWrite:false})));
// local web + many cross filaments
{const v=[];for(let i=0;i<points.length;i++){const ds=[];for(let j=0;j<points.length;j++)if(i!==j)ds.push([points[i].distanceToSquared(points[j]),j]);ds.sort((a,b)=>a[0]-b[0]);for(let k=0;k<4;k++){const j=ds[k][1];if(i<j)v.push(points[i].x,points[i].y,points[i].z,points[j].x,points[j].y,points[j].z)}}for(let q=0;q<95;q++){const a=Math.floor(rnd()*points.length),b=Math.floor(rnd()*points.length);if(a!==b)v.push(points[a].x,points[a].y,points[a].z,points[b].x,points[b].y,points[b].z)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(v,3));core.add(new THREE.LineSegments(g,new THREE.LineBasicMaterial({color:C.soft,transparent:true,opacity:.34,blending:THREE.AdditiveBlending})))}
// irregular curved filaments around/through core -- never circles
const filamentGroup=new THREE.Group();root.add(filamentGroup);
for(let i=0;i<18;i++){const a=rnd()*Math.PI*2,r=.65+rnd()*.75,p0=new THREE.Vector3(Math.cos(a)*r,Math.sin(a)*r*.9,(rnd()-.5)*.1),p3=new THREE.Vector3(Math.cos(a+1.2+rnd()*2.5)*r,Math.sin(a+1.2+rnd()*2.5)*r*.9,(rnd()-.5)*.1),p1=p0.clone().multiplyScalar(.25+rnd()*.45).add(new THREE.Vector3((rnd()-.5)*.65,(rnd()-.5)*.65,0)),p2=p3.clone().multiplyScalar(.25+rnd()*.45).add(new THREE.Vector3((rnd()-.5)*.65,(rnd()-.5)*.65,0)),curve=new THREE.CubicBezierCurve3(p0,p1,p2,p3),g=new THREE.BufferGeometry().setFromPoints(curve.getPoints(55)),m=new THREE.LineBasicMaterial({color:i%4===0?C.gold:C.red,transparent:true,opacity:.10+rnd()*.07,blending:THREE.AdditiveBlending});filamentGroup.add(new THREE.Line(g,m))}
// small hot nucleus, no large red disk
const nucleus=new THREE.Group();root.add(nucleus);const h1=sprite(C.red,.72,.075),h2=sprite(C.gold,.55,.11),h3=sprite(C.soft,.34,.72),h4=sprite(C.white,.12,1);nucleus.add(h1,h2,h3,h4);
const sparks=new THREE.Group();root.add(sparks);for(let i=0;i<120;i++){const a=rnd()*Math.PI*2,r=.12+rnd()*1.3,s=sprite(i%5===0?C.red:i%4===0?C.gold:C.soft,.026+rnd()*.022,.68);s.position.set(Math.cos(a)*r,Math.sin(a)*r*.88,(rnd()-.5)*.18);s.userData={base:s.position.clone(),phase:rnd()*Math.PI*2};sparks.add(s)}
const memories=[];function spawnMemory(){const d=orbits[Math.floor(rnd()*orbits.length)],s=sprite(rnd()>.45?C.soft:C.gold,.16,1);s.position.set(0,0,.06);root.add(s);memories.push({sprite:s,orbit:d,angle:rnd()*Math.PI*2,speed:(.08+rnd()*.1)*(rnd()>.5?1:-1),age:0,launch:1.2})}
let paused=false;addEventListener('keydown',e=>{if(e.key.toLowerCase()==='m')spawnMemory();if(e.key==='Escape')paused=!paused});const clock=new THREE.Clock();let t=0;
function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.05);if(!paused){t+=dt;orbitGroup.rotation.z=Math.sin(t*.075)*.018;core.rotation.z-=dt*.014;core.rotation.x=Math.sin(t*.16)*.025;filamentGroup.rotation.z+=dt*.012;nucleus.scale.setScalar(1+Math.sin(t*2.15)*.025);h3.material.opacity=.67+Math.sin(t*2.65)*.07;for(const c of orbitGroup.children)if(c.isSprite&&c.userData.orbit){c.userData.angle+=c.userData.speed*dt;c.position.copy(orbitPoint(c.userData.orbit,c.userData.angle))}for(const s of sparks.children){const p=s.userData.base,w=1+Math.sin(t*1.5+s.userData.phase)*.035;s.position.set(p.x*w,p.y*w,p.z)}for(const m of memories){m.age+=dt;m.angle+=m.speed*dt;const target=orbitPoint(m.orbit,m.angle),u=Math.min(1,m.age/m.launch),e=1-Math.pow(1-u,3);m.sprite.position.lerpVectors(new THREE.Vector3(0,0,.06),target,e);m.sprite.scale.setScalar(.16*(.35+.65*e))}}composer.render()}
animate();addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);composer.setSize(innerWidth,innerHeight)});
